/**
 * This file was automatically generated by GraphQL Nexus
 * Do not make changes to this file directly
 */

import {core} from 'nexus';
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    date<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.ScalarInputFieldConfig<
        core.GetGen3<'inputTypes', TypeName, FieldName>
      >,
    ): void; // "Date";
    time<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.ScalarInputFieldConfig<
        core.GetGen3<'inputTypes', TypeName, FieldName>
      >,
    ): void; // "Time";
    datetime<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.ScalarInputFieldConfig<
        core.GetGen3<'inputTypes', TypeName, FieldName>
      >,
    ): void; // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    date<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "Date";
    time<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "Time";
    datetime<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "DateTime";
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {}

export interface NexusGenEnums {}

export interface NexusGenRootTypes {
  Category: {
    // root type
    description?: string | null; // String
    id: string; // ID!
    name: string; // String!
    slug: string; // String!
  };
  Gallery: {
    // root type
    description?: string | null; // String
    id: string; // ID!
    image: string; // String!
    name: string; // String!
    slug: string; // String!
  };
  GalleryImage: {
    // root type
    full: string; // String!
    medium: string; // String!
  };
  Post: {
    // root type
    content?: string | null; // String
    description?: string | null; // String
    id: string; // ID!
    image?: string | null; // String
    name: string; // String!
    slug: string; // String!
  };
  Query: {};
  Tag: {
    // root type
    description?: string | null; // String
    id: string; // ID!
    name: string; // String!
    slug: string; // String!
  };
  CreatedAt: NexusGenRootTypes['Post'];
  Node:
    | NexusGenRootTypes['Category']
    | NexusGenRootTypes['Post']
    | NexusGenRootTypes['Gallery']
    | NexusGenRootTypes['Tag'];
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  Date: any;
  DateTime: any;
  Time: any;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {}

export interface NexusGenFieldTypes {
  Category: {
    // field return type
    description: string | null; // String
    id: string; // ID!
    name: string; // String!
    slug: string; // String!
  };
  Gallery: {
    // field return type
    description: string | null; // String
    id: string; // ID!
    image: string; // String!
    images: NexusGenRootTypes['GalleryImage'][] | null; // [GalleryImage!]
    name: string; // String!
    slug: string; // String!
  };
  GalleryImage: {
    // field return type
    full: string; // String!
    medium: string; // String!
  };
  Post: {
    // field return type
    categories: NexusGenRootTypes['Category'][]; // [Category!]!
    content: string | null; // String
    createdAt: any; // DateTime!
    description: string | null; // String
    id: string; // ID!
    image: string | null; // String
    name: string; // String!
    slug: string; // String!
  };
  Query: {
    // field return type
    author: string; // String!
    categoryBySlug: NexusGenRootTypes['Category']; // Category!
    featuredList: NexusGenRootTypes['Post'][]; // [Post!]!
    gallery: NexusGenRootTypes['Gallery']; // Gallery!
    galleryList: NexusGenRootTypes['Gallery'][]; // [Gallery!]!
    newestList: NexusGenRootTypes['Post'][]; // [Post!]!
    post: NexusGenRootTypes['Post']; // Post!
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
    recentList: NexusGenRootTypes['Post'][]; // [Post!]!
  };
  Tag: {
    // field return type
    description: string | null; // String
    id: string; // ID!
    name: string; // String!
    slug: string; // String!
  };
  CreatedAt: {
    // field return type
    createdAt: any; // DateTime!
  };
  Node: {
    // field return type
    id: string; // ID!
  };
}

export interface NexusGenArgTypes {
  Query: {
    categoryBySlug: {
      // args
      slug: string; // String!
    };
    featuredList: {
      // args
      limit?: number | null; // Int
    };
    gallery: {
      // args
      slug: string; // String!
    };
    galleryList: {
      // args
      limit?: number | null; // Int
    };
    newestList: {
      // args
      limit?: number | null; // Int
    };
    post: {
      // args
      slug: string; // String!
    };
    posts: {
      // args
      id: number; // Int!
    };
    recentList: {
      // args
      limit?: number | null; // Int
    };
  };
}

export interface NexusGenAbstractResolveReturnTypes {
  CreatedAt: 'Post';
  Node: 'Category' | 'Post' | 'Gallery' | 'Tag';
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames =
  | 'Category'
  | 'Gallery'
  | 'GalleryImage'
  | 'Post'
  | 'Query'
  | 'Tag';

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = 'CreatedAt' | 'Node';

export type NexusGenScalarNames =
  | 'Boolean'
  | 'Date'
  | 'DateTime'
  | 'Float'
  | 'ID'
  | 'Int'
  | 'String'
  | 'Time';

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes:
    | NexusGenTypes['inputNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['scalarNames'];
  allOutputTypes:
    | NexusGenTypes['objectNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['unionNames']
    | NexusGenTypes['interfaceNames']
    | NexusGenTypes['scalarNames'];
  allNamedTypes:
    | NexusGenTypes['allInputTypes']
    | NexusGenTypes['allOutputTypes'];
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {}
  interface NexusGenPluginSchemaConfig {}
}
