name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Get the version
        run: echo ::set-env name=APP_VERSION::${GITHUB_REF#refs/tags/v}

      - name: Build and publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master

        with:
          name: nghiepit/botble-graphql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest,${{ env.APP_VERSION }}'
          buildargs: APP_VERSION

      - name: Refresh Docker badge
        run: wget --method=POST https://hooks.microbadger.com/images/nghiepit/botble-graphql/mXtVqDDfF9C-Fq6igYA9PZzEGUU= -O /dev/null || exit 0
